#!/usr/bin/env bash
# a bash script similar to task 0 but
# less code lines are used for it.

if ! service nginx status | grep -q "active (running)"; then
	apt-get update
	apt-get -y install nginx
	sed -i 's/#.*listen 80;/listen 80;/g' /etc/nginx/sites-available/default
	systemctl restart nginx
fi
