#!/usr/bin/env bash
# This script shows 'To infinity and beyond' indefintely
# Requirement: In between each iteration of the loop, add a sleep 2

trap 'echo "Iam invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
